#!/bin/bash -x

num1=60
num2=40
AREAINFEET=$(($num1*$num2))
echo $AREAINFEET
AREAINMETERS=$(($AREAINFEET/10))
echo $AREAINMETERS
AREAOF25PLOT=$(($AREAINMETERS*25))
echo $AREAOF25PLOT
AREAINACERS=$(($AREAOF25PLOT/4047))
echo $AREAINACERS
